// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGRtduNue5mBQrOjvzeyLCkjFlru4GZhA',
    appId: '1:146640858854:web:94ffaa75fe2afb94ff9527',
    messagingSenderId: '146640858854',
    projectId: 'mobi-health-5ef9d',
    authDomain: 'mobi-health-5ef9d.firebaseapp.com',
    storageBucket: 'mobi-health-5ef9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgHpv66nLssBAgZErqLui433JHpN8EYEw',
    appId: '1:146640858854:android:67dc7b116a0399e1ff9527',
    messagingSenderId: '146640858854',
    projectId: 'mobi-health-5ef9d',
    storageBucket: 'mobi-health-5ef9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5k32GLH5nsYaQ2QW7SCvNSqPhjI_P7Oo',
    appId: '1:146640858854:ios:997810c388177b58ff9527',
    messagingSenderId: '146640858854',
    projectId: 'mobi-health-5ef9d',
    storageBucket: 'mobi-health-5ef9d.appspot.com',
    iosBundleId: 'com.example.mobiHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5k32GLH5nsYaQ2QW7SCvNSqPhjI_P7Oo',
    appId: '1:146640858854:ios:997810c388177b58ff9527',
    messagingSenderId: '146640858854',
    projectId: 'mobi-health-5ef9d',
    storageBucket: 'mobi-health-5ef9d.appspot.com',
    iosBundleId: 'com.example.mobiHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGRtduNue5mBQrOjvzeyLCkjFlru4GZhA',
    appId: '1:146640858854:web:72d088dc838913afff9527',
    messagingSenderId: '146640858854',
    projectId: 'mobi-health-5ef9d',
    authDomain: 'mobi-health-5ef9d.firebaseapp.com',
    storageBucket: 'mobi-health-5ef9d.appspot.com',
  );

}